spring.datasource.url=jdbc:postgresql://localhost:5432/prayer_app
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.flyway.url=jdbc:postgresql://localhost:5432/prayer_app
spring.flyway.user=${DB_USERNAME}
spring.flyway.password=${DB_PASSWORD}

jwt.signing-key=459b5631306a7ec4573e52e83bcc1a22ce2e19682f5e31bb965a9709f1fd99c1