openapi: 3.0.3

info:
  title: Prayer App Services
  description: |-
    This is the API that supports the Prayer App.
  version: 1.0.0
servers:
  - url: http://localhost:8080

tags:
  - name: User

paths:
  /api/user:
    post:
      tags:
        - User
      summary: Creates a new user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUserRequest"
      responses:
        200:
          description: User added successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserTokenPair"
  /api/user/token:
    get:
      tags:
        - User
      summary: Generates a user token pair based on a refresh token in the header
      operationId: generateTokensFromRefreshToken
      security:
        - bearerAuth: []
      responses:
        200:
          description: User Token Pair generated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserTokenPair"
    post:
      tags:
        - User
      summary: Generates an user token pair based on the user's username and password
      operationId: generateTokensFromLogin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCredentials"
      responses:
        200:
          description: Token generated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserTokenPair"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    CreateUserRequest:
      description: Request for signup route
      type: object
      properties:
        username:
          description: The user's username
          type: string
        fullName:
          description: The user's full name
          type: string
        email:
          description: The user's email
          type: string
          format: email
        password:
          description: The user's password
          type: string
      required:
        - username
        - fullName
        - email
        - password
    UserCredentials:
      description: Request to generate a token using the user's credentials
      type: object
      properties:
        username:
          description: The user's username
          type: string
        password:
          description: The user's password
          type: string
    UserTokenPair:
      description: The user's authentication token and refresh token
      type: object
      properties:
        authToken:
          description: The authentication token used to access API routes that require JWT tokens
          type: string
        refreshToken:
          description: The refresh token used to get a new auth token when it expires
          type: string